### PR TITLE
Fixed an error in the detection of micro:bit UART

### PR DESCRIPTION
**Pull request by anandology**
Replaced the text parsing logic with a regular expression for more
robust matching of the device id.

### CODE REVIEW

**Comment by anandology** [comment]
Fixes #13

**Comment by carlosperate** [comment]
Looks good to me based on how microrepl is currently parsing the USB com ports VID and PID (by parsing the `hwid` from the `ListPortInfo` array returned by `serial.tools.list_ports.comports()`). 👍 


Looking at the pyserial documentation (http://pyserial.readthedocs.io/en/latest/tools.html) instead of doing it this way we can probably check if any of the returned `ListPortInfo` instances has valid `pid` and `vid` variables. However, since we would need to check if this feature is version-dependent, and test it in all platforms (specially taking in consideration raspbian jessie has a very old version of pyinstaller), it's probably better to merge this to fix current master and then open an issue as a reminder that this is something we could improve.

**Comment by carlosperate** [comment]
@ntoll anything blocking this one? I've tested it in macOS and fixes issue #13.

**Comment by ntoll** [comment]
Thanks for the kick @carlosperate.

@anandology thank you for your contribution, apologies for the delay on my part.

**Pull request merged**
